### ISSUE TITLE
Initial commit

### ISSUE THREAD

**Issue by conzett** [megalodoc/megalodoc#1]
Make an initial commit with create-react-app. Include storybooks, ES Lint (or equivalent) and add necessary Webpack plugins.

**Comment by daveshah** [comment]
@conzett I went ahead and just pushed the bare-bones react app generated with create-react-app and the basic storybook setup. I was unsure what else to add as far as ES Lint / Webpack plugins. I saw that [create-react-app mentions](https://github.com/facebookincubator/create-react-app#get-started-immediately) that this might already be done but I'm not as familiar with the js eco-system so I was a bit unsure and thought I'd get your feedback on what else you thought we'd need.

**Comment by conzett** [comment]
@daveshah 👍 - I can take a look and add anything else that we might need in the next commit.

**Comment by conzett** [comment]
Going to consider this one done after review. Will add more later if needed 👍
