### ISSUE TITLE
Add ESLint to CI

### ISSUE THREAD

**Issue by conzett** [megalodoc/megalodoc#17]
Fail if not conforming

**Comment by austenmadden** [comment]
@conzett Thoughts on this [npm package?](https://www.npmjs.com/package/travis-github-lint-status). I like the idea of separating the linter from the CI test run.

**Comment by conzett** [comment]
@austenmadden is there a way to just configure Travis to run two different jobs without this package? I thought there was but its been a long time since I've set up Travis. That package doesn't seem to get a lot of use.

**CC:** @daveshah since you configured this initially.

**Comment by austenmadden** [comment]
@conzett More than likely, I was just curious if that was considered to be a useful shortcut.

**Comment by daveshah** [comment]
*I think* we can just add something under the (yet to be added) `jobs` section of our `travis.yml` (as an example, see [this](https://github.com/superwolff/metalsmith-in-place/blob/master/.travis.yml))

**Comment by daveshah** [comment]
@conzett & @austenmadden let me know if [this](https://travis-ci.org/megalodoc/megalodoc/builds/240607203?utm_source=github_status&utm_medium=notification) is what you had in mind as far as splitting out the jobs :)
Also, I've never added a js linter so :crossed_fingers: things look aok as far as a start on that end too.
