### ISSUE TITLE
Add mockups

### ISSUE THREAD

**Issue by conzett** [megalodoc/megalodoc#4]
These will just be rough and layout a what the MVP should look like

**Comment by conzett** [comment]
![Initial mockup](https://raw.githubusercontent.com/megalodoc/megalodoc-mockups/3c1f92d5d77259d33114e88bf6c65fa31b34b236/main.png)

This is just a rough first stab to get us started. I can move it to the wiki after we get some feedback.

**Comment by daveshah** [comment]
Wondering if we'll be referencing tags anywhere in the UI? From a user perspective, I feel like these help in understanding what resources (from a higher level) a consumer of the api may want to work with.

**Comment by conzett** [comment]
@daveshah - I was planning on using them to construct the tree view seen on the right with the tag being the top level item. I'll clear that up and also reference the tag name in the page itself.

Thoughts on adding mock-ups to a Wiki rather than keeping them here?

**Comment by daveshah** [comment]
Cool - was curious about that. 
As far as moving to the wiki, I'm in favor. I think once it's there we can close this out 👍

**Comment by conzett** [comment]
Latest version has been updated to show the tree view and tags 👍 
Mockups page added to wiki here: https://github.com/megalodoc/megalodoc/wiki/Mockups
New repository created so we don't bloat this one: https://github.com/megalodoc/megalodoc-mockups

I think I'm good calling this one "done".
